webhooks:
  - name: "all"
    junk_url: "https://webhooks.aycd.io/webhooks/api/v1/send/29324/2375296d-ba96-422b-bb55-e5088d60cfee"
    unfiltered_url: "https://webhooks.aycd.io/webhooks/api/v1/send/29242/5dfe54b4-34a1-4de1-a717-cb3aa64a36f7"
    filtered_url: "https://webhooks.aycd.io/webhooks/api/v1/send/29241/2aa0a599-a808-4584-a6ff-f86d30117009"
    keywords:
      - "ninja"
      - "irobot"
      - "roomba"
      - "keurig"
      - "shark"
      - "bissell"
      - "dyson"
      - "nest"
      - "dji"
      - "3070"
      - "3080"
      - "3090"
      - "4060"
      - "4070"
      - "4080"
      - "4090"
      - "6700 xt"
      - "6800 xt"
      - "6900 xt"
      - "7600 xt"
      - "7700 xt"
      - "7800 xt"
      - "7900 xt"
      - "9060 xt"
      - "9070 xt"
      - "9080 xt"
      - "victrola"
      - "instant pot"
      - "evenflo"
      - "dewalt"
      - "milwaukee"
      - "g.skill"
      - "gskill"
    asins:
      - "B0BQSC4XNL"

  - name: "dev lab"
    junk_url: "https://discord.com/api/webhooks/1499711458706063471/ZfpqzzJjizsADHFbGsiHpMwWgpIIWBeOooWqsPsDuIEwrwko_Yt3oKGeD6IvBLBRC266"
    unfiltered_url: "https://discord.com/api/webhooks/1499711496278642769/kBNt3llN1rFwjyi5aqKOftFoFDFWCysjaHN5TAGnF1IJKJEMVEF0bQ2hiGjeuQCvCJPq"
    filtered_url: "https://discord.com/api/webhooks/1499711530831314965/b64thtLGsm83zjLu7X8surz2GTgxJnDr73Yp86l7HLDkaZBVUD54BZLB_q0wLJAPD2Am"
    keywords:
      - "ninja"
      - "irobot"
      - "roomba"
      - "keurig"
      - "shark"
      - "bissell"
      - "dyson"
      - "nest"
      - "dji"
      - "3070"
      - "3080"
      - "3090"
      - "4060"
      - "4070"
      - "4080"
      - "4090"
      - "6700 xt"
      - "6800 xt"
      - "6900 xt"
      - "7600 xt"
      - "7700 xt"
      - "7800 xt"
      - "7900 xt"
      - "9060 xt"
      - "9070 xt"
      - "9080 xt"
      - "victrola"
      - "instant pot"
      - "evenflo"
      - "dewalt"
      - "milwaukee"
      - "g.skill"
      - "gskill"
    asins:
      - "B0BQSC4XNL"
